@echo off
echo Installing Stage Timer App...
set "INSTALL_DIR=%LOCALAPPDATA%\Stage Timer App"
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"
echo Extracting files...
powershell -Command "Expand-Archive -Path '%~dp0Stage-Timer-App-Optimized.zip' -DestinationPath '%INSTALL_DIR%' -Force"
echo Creating shortcuts...
powershell -Command "$WshShell = New-Object -comObject WScript.Shell; $Shortcut = $WshShell.CreateShortcut('%USERPROFILE%\Desktop\Stage Timer.lnk'); $Shortcut.TargetPath = '%INSTALL_DIR%\stage-timer-app.exe'; $Shortcut.Save()"
echo Installation complete!
echo Starting Stage Timer App...
start "" "%INSTALL_DIR%\stage-timer-app.exe"
pause
